image: python:3.8-slim

variables:
  GIT_STRATEGY: clone

stages:         
  - mirror


mirror_to_github:
  stage: mirror
  script:
    - apt-get update -qy  # Update package list
    - apt-get install -y git 
    - git remote add github https://$GITHUB_TOKEN@github.com/dinuka-p/supervisor-finder.git
    - git push github main
  only:
    - main
