image: alpine/git:latest


stages:         
  - mirror


mirror_to_github:
  stage: mirror
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/dinuka-p/supervisor-finder.git
    - git checkout -b main 
    - git push github main
  only:
    - main
