version: '3.7'

services:
  frontend:
    image: projectimage:frontend
    build: ssa-frontend
    ports:
      - "3001:80"
    restart: always

  backend:
    image: projectimage:backend
    build: ssa-backend
    ports:
      - "5001:5000"
    restart: always
    environment:
      DB_PW: "${DB_PW}"
      DB_HOST: fyp-db.mysql.database.azure.com
      DB_NAME: supervisor_finder_db
      DB_USER: dinuka


secrets:
  db_password:
    file: .env
