version: '3.7'

services:
 frontend:
    image: node:14
    container_name: frontend
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run build"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend_network

 backend:
    image: python:3.8-slim
    container_name: backend
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "pip install --trusted-host pypi.python.org -r requirements.txt && python run.py"
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DB}
    networks:
      - frontend_network

 db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - frontend_network

volumes:
 db_data:

networks:
 frontend_network:
    driver: bridge