version: '3.7'

services:
  frontend:
    image: projectimage:frontend
    build: ssa-frontend
    ports:
      - "3001:80"
    restart: always

  backend:
    image: projectimage:backend
    build: ssa-backend
    ports:
      - "5001:5000"
    restart: always
    environment:
      DB_PW: "${MYSQL_ROOT_PASSWORD}"
      DB_HOST: db


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: supervisor_allocation_db
    # networks:
    #   - app_network

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt

volumes:
 db_data:

# networks:
#  app_network:
#     driver: bridge